"use client";
import {useEffect,useRef,useState} from "react";
import {initialEntries,assetSrc,type Entry} from "../lib/archive";

type ApiData={entries:Entry[];error?:string};
type View="home"|"news"|"past"|"about"|"contact"|"entry";
export default function Archive() {
  const [entering,setEntering]=useState(false);
  const [view,setView]=useState<View>("home"),[published,setPublished]=useState<Entry[]>(initialEntries),[detail,setDetail]=useState("");
  const [loaded,setLoaded]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const timer=setTimeout(()=>{for(const src of new Set(["/assets/logo.webp",...published.filter(entry=>entry.section==="news").slice(0,3).map(entry=>entry.image).filter(Boolean)])){const image=new Image();image.src=assetSrc(src);void image.decode().catch(()=>{});}},1200);return()=>clearTimeout(timer);},[published]);
  const liveEntries=useRef(published);liveEntries.current=published;
  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[{name:"read_archive_entries",description:"Read the published News and Past events entries.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({entries:liveEntries.current})},{name:"open_archive_section",description:"Navigate the visible archive to News or Past events.",inputSchema:{type:"object",properties:{section:{type:"string",enum:["news","past"]}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const value=input as {section?:string};if(!value||!["news","past"].includes(value.section||""))throw new Error("Choose news or past.");location.hash=value.section!;setView(value.section as View);return {section:value.section};}}];
    for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error);}catch(error){console.error(error);}}
    return()=>lifecycle.abort();
  },[]);
  useEffect(()=>{const sync=()=>{setEntering(false);const hash=location.hash.slice(1);if(hash.startsWith("entry/")){setDetail(hash.slice(6));setView("entry");}else setView((["news","past","about","contact"].includes(hash)?hash:"home") as View);};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync);},[]);

  useEffect(()=>{if(!entering)return;const duration=window.matchMedia("(prefers-reduced-motion: reduce)").matches?50:2400;const timer=setTimeout(()=>{location.hash="news";setEntering(false);},duration);return()=>clearTimeout(timer);},[entering]);
  useEffect(()=>{fetch(import.meta.env.BASE_URL+"archive.json",{cache:"no-store"}).then(async r=>{const data=await r.json() as ApiData;if(!r.ok)throw new Error(data.error);setPublished(data.entries);setLoaded(true);}).catch(e=>setError(e.message));},[]);
  const logo=<a href="#home" className="logo" aria-label="Diaspora East Cinema home"><img className="logo-color" src={assetSrc("/assets/logo.webp")} alt="Diaspora East Cinema"/><span className="logo-hover" aria-hidden="true"><img src={assetSrc("/assets/logo-white.webp")} alt=""/></span></a>;
  const cards=published.filter(e=>e.section===view), item=published.find(e=>e.id===detail);
  return <>{(view==="home"||entering)&&<button className={"opening"+(entering?" opening-leaving":"")} disabled={entering} onClick={()=>{setView("news");setEntering(true);}} aria-label="Enter Diaspora East Cinema"><svg width="0" height="0" className="sea-filter" aria-hidden="true"><defs><filter id="sea-ripple" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency="0.006 0.04" numOctaves="2" seed="8" result="waves"/><feOffset in="waves" dx="0" dy="0" result="flow"><animate attributeName="dx" values="-30;30;-30" dur="5s" repeatCount="indefinite"/></feOffset><feColorMatrix in="flow" type="matrix" values="1 0 0 0 0  0 0 0 0 0.5  0 0 0 0 0  0 0 0 0 1" result="horizontal-flow"/><feDisplacementMap in="SourceGraphic" in2="horizontal-flow" scale="24" xChannelSelector="R" yChannelSelector="G"/></filter></defs></svg><img className="opening-background" fetchPriority="high" decoding="async" src={assetSrc("/assets/home-background.webp")} alt=""/><img className="opening-water" src={assetSrc("/assets/home-background.webp")} alt="" aria-hidden="true"/><span className="seagull-flight flight-one" aria-hidden="true"><img className="seagull" src={assetSrc("/assets/seagull.gif")} alt=""/></span><span className="seagull-flight flight-two" aria-hidden="true"><img className="seagull" src={assetSrc("/assets/seagull.gif")} alt=""/></span><img className="opening-logo" fetchPriority="high" decoding="async" src={assetSrc("/assets/logo-animated.webp")} alt="Diaspora East Cinema"/></button>}{view==="home"?null:
    <div className="site"><aside className="site-sidebar">{logo}<nav>{[["news","News"],["past","Past events"],["about","About"],["contact","Contact"]].map(([route,label])=><a href={"#"+route} key={route} className={view===route?"active":""} aria-current={view===route?"page":undefined}>{label}</a>)}</nav></aside><main className="site-main">{(view==="news"||view==="past")?<><div className="card-grid">{cards.map(e=><a key={e.id} className="card" href={"#entry/"+e.id}><div className="cover">{e.image?<img src={assetSrc(e.image)} decoding="async" loading="lazy" alt=""/>:<div className="placeholder">SHARED<br/>REALITIES</div>}{(e.date||e.description)&&<div className="card-overlay">{e.description&&<p><span>{e.description}</span></p>}{e.date&&<p><span>{e.date}</span></p>}</div>}</div><h2>{e.title}</h2></a>)}</div>{cards.length===0&&<p className="empty">No entries published yet.</p>}{error&&!loaded&&<p className="public-error" role="status">{error}</p>}</>:view==="entry"?<article className="article"><a href={item?.section==="past"?"#past":"#news"} className="back">Back to {item?.section==="past"?"Past events":"News"}</a>{item?<>{item.image&&<img className="detail-cover" src={assetSrc(item.image)} decoding="async" alt=""/>}<p className="category">{item.category}</p><h1>{item.title}</h1>{item.date&&<p>{item.date}</p>}<p className="description">{item.description}</p></>:<h1>Entry not found</h1>}</article>:<article className="article info-page"><h1>{view==="about"?"About":"Contact"}</h1><p>Diaspora East Cinema</p><p className="muted">{view==="about"?"About text has not been provided yet.":"Contact details have not been provided yet."}</p></article>}</main></div>}</>;
}
